### ISSUE TITLE
The mod just close

### ISSUE THREAD

**Issue by JuanpacrXD** [SFGrenade/StoriesOfaHkPlayer-Ch1#1]
when i oppen the game with this mode i cant do anything more than see the tittle and the menu go to exit the game

**Comment by SFGrenade** [comment]
that's what the mod does

**Comment by JuanpacrXD** [comment]
so what its the point?

**Comment by SFGrenade** [comment]
unique storytelling, over multiple chapters (from which currently only this one exists)
